### ISSUE TITLE
Javascript Error: Uncaught TypeError: Cannot read property 'id' of undefined - File media-editor.min.js

### ISSUE THREAD

**Issue by fdaciuk** [bangbay/wp-user-avatar#1]
This error happens in front of the site, to activate the plugin.

**Comment by bangbay** [comment]
Could you provide more info about what brought about the error? What version of WordPress were you using? Which theme? Do you have other plugins activated? Where you using the code in this repository or did you download the current release from the WordPress repository?

**Comment by fdaciuk** [comment]
Sorry @bangbay, actually I scored it would try to adjust here and send a pull request :)

But the following happens: I disabled all plugins and I enabled only the WP User Avatar, and only gives him the problem.

The theme was created by me. I am using the latest version of WP. I downloaded the WordPress plugin repository.
