### ISSUE TITLE
Load jquery in footer instead of header

### ISSUE THREAD

**Issue by bramwillemse** [bangbay/wp-user-avatar#3]
Hi there, I'm used to loading all my jquery in the footer. Would be great to have a setting or code snippet to load it there. It would fix this problem for me (not sure what it does, but it comes back at every page and is loaded before jquery has been loaded..)

  `<script type="text/javascript">
      jQuery(function(){
Uncaught ReferenceError: jQuery is not defined
        jQuery('#your-profile').attr('enctype', 'multipart/form-data');
      });
    </script>
`

Thanks!

**Comment by bramwillemse** [comment]
For now I've hacked the plugin code and replaced wp_head with wp_footer on line 171 of wp-user-avatar.php but would be great to have the option built in, imo!

**Comment by bangbay** [comment]
Thanks for bringing this to my attention. I am probably going to move this code in the next plugin version.

**Comment by bramwillemse** [comment]
cool, thanks! :+1: 

And thanks for the nice plugin. It's the best one for profile pics I could find in a long search for a good one ;)
