### ISSUE TITLE
Front end profile avatar

### ISSUE THREAD

**Issue by festaans** [bangbay/wp-user-avatar#4]
Hi, I will try to sift through your code but incase anyone already have the solution, here goes: We have a front end profile and currently make use of a custom user meta field to store the attachment ID of "profile pics" user upload. The problem is that it currently have no connection to the wordpress user avatar and we need to call our custom image everywhere the avatar normally appear. How would one go about using your plugin as the intermediate step to get our image (which resides in the media library) to be the actual user avatar? Any ideas?

**Comment by festaans** [comment]
I've realised that do_action('edit_user_profile',$current_user); returns the Avatar profile section on our front-end profile. The problem is that we currently use do_action('edit_user_profile',$current_user); in more than one place as we split the profile into sections. Still digging...

**Comment by bangbay** [comment]
Hi, I'm not completely sure I understand what it is you want to do, but if you've created a custom avatar field, yet still want to use the functions I've created in my plugin, you can change the name of your user meta field to match what I use. The attachment ID would be saved in a meta field called $wpdb->get_blog_prefix($blog_id).'user_avatar' where $wpdb->get_blog_prefix($blog_id) is the prefix you're using for your database tables. For example, if you're using wp_ as your prefix, the user meta field would be called wp_user_avatar.

**Comment by festaans** [comment]
Cool, sorted. Thanks
